package com.codefactory.petmanager.g12.petmanager_backend.mapper;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.codefactory.petmanager.g12.petmanager_backend.dto.RoleDTO;
import com.codefactory.petmanager.g12.petmanager_backend.dto.UserRequestDTO;
import com.codefactory.petmanager.g12.petmanager_backend.dto.UserResponseDTO;
import com.codefactory.petmanager.g12.petmanager_backend.entities.Role;
import com.codefactory.petmanager.g12.petmanager_backend.entities.User;

@Mapper(componentModel = "spring")
public interface UserMapper {

  @Mapping(source = "role", target = "role")
  UserResponseDTO userToUserResponseDTO(User user);

  @Mapping(source = "roleId", target = "role.id")
  @Mapping(target = "id", ignore = true) // Autogenerated
  User userRequestDTOToUser(UserRequestDTO userRequestDTO);

  RoleDTO roleToRoleDTO(Role role);

  List<UserResponseDTO> usersToUserResponseDTOs(List<User> users);
  List<RoleDTO> rolesToRoleDTOs(List<Role> roles);
  
}